This is a mobile version portfolio
oluwajuwon8/Portfolio pull request #2
Opened 2021-09-22 22:05 UTC by oluwajuwon8

The work section was added to my mobile version portfolio.

2021-09-22 22:22 UTC, george-shammar requested changes
Hi @oluwajuwon8 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with failing linters.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-09-23 22:04 UTC, TedLivist requested changes
Hi @oluwajuwon8,

Good job so far! You have done well setting up the linters.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-23 22:04 UTC, TedLivist commented on index.html
> +    </div>
- [ ] Your entire **WORKS** section should be wrapped in a `<section>` tag

-  [ ] Your design also looks very different from what is on the template. Please, your UI should look as similar to the template as possible.

**Your design:**
![aziz-des](https://user-images.githubusercontent.com/36542986/134586150-c1689866-1030-4e2c-8477-2ac860dddb40.jpg)

**Template:**
![chidi-backg](https://user-images.githubusercontent.com/36542986/134586177-872452b0-c9ff-40a1-b904-7959e91bd4ee.jpg)

- [ ] The main container of the projects should have `display: grid`

2021-09-23 22:04 UTC, TedLivist commented on index.html
> +        </button>
- [ ] Please each project should be wrapped in a different container.
- [ ] Each project container should also be displayed with a flexbox.
- [ ] Your projects currently have no titles. Please each project should have a title like **'Profesional Art Printing Data'** as defined in the Figma template.
- [ ] The title of each project should be wrapped in a `hx` tag.
- [ ] Each of your projects has no description paragraph as defined in the Figma template. Please add a description wrapped in a `<p>` tag.
- [ ] There also seems to be an issue with indentation the closing tag of your `a` tags. Please fix it.

2021-09-23 22:04 UTC, TedLivist commented on index.html
> +    <button id="button" type="submit">See Project</button>
- [ ] All your **'See Project'** buttons should have stylings for `:active`. Currently, you only have styling for `:hover`.

2021-09-23 22:04 UTC, TedLivist commented on index.html
> +      <div id="ground"><img src="Group2.png" alt=""/></div>
- [ ] Your background image should be set from the CSS, not `<img>` tag. Please fix this.
- [ ] Also there seems to be an issue with your overall design. It is quite different from what is in the template. Please stick to the template as much as possible.

![aziz-about](https://user-images.githubusercontent.com/36542986/134589310-3224d019-d1f9-4f63-82a8-8b24e4eeea97.jpg)

2021-09-23 22:04 UTC, TedLivist commented on index.html
> +      </h3>
- [ ] Please wrap this description in a `p` tag, not `hx` tag

2021-09-23 22:04 UTC, TedLivist commented on index.html
> +      <button id="Resume" type="submit">Get My Resume</button>
- [ ] The font of your button is quite large compared to what is on the template. Please reduce it.
- [ ] Your button should also have more horizontal padding as in the template.
- [ ] Add stylings for `:active` and `hover` for your button

![btns-styles](https://user-images.githubusercontent.com/36542986/134590624-ff1610f5-2789-4f9d-85a2-38bf12bf3edf.jpg)

2021-09-23 22:04 UTC, TedLivist commented on index.html
> +      </div>
- [ ] Please wrap your **'Languages'**, **'Frameworks'** and **'Skills'** categories in a `ul` with each of them in a `li` tag

![langs](https://user-images.githubusercontent.com/36542986/134589830-1b61230c-13dd-48d8-87f1-039102a15de9.jpg)

2021-09-24 15:01 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-09-24 15:02 UTC, merged